basic.forever(function () {
    basic.pause(5000)
    music.playTone(262, music.beat(BeatFraction.Quarter))
    basic.pause(30)
    music.playTone(262, music.beat(BeatFraction.Quarter))
    basic.pause(30)
    music.playTone(294, music.beat(BeatFraction.Quarter))
    basic.pause(30)
    music.playTone(262, music.beat(BeatFraction.Quarter))
    basic.pause(30)
    music.playTone(349, music.beat(BeatFraction.Quarter))
    basic.pause(30)
    music.playTone(330, music.beat(BeatFraction.Quarter))
    basic.pause(100)
    music.playTone(262, music.beat(BeatFraction.Quarter))
    basic.pause(30)
    music.playTone(262, music.beat(BeatFraction.Quarter))
    basic.pause(30)
    music.playTone(294, music.beat(BeatFraction.Quarter))
    basic.pause(30)
    music.playTone(262, music.beat(BeatFraction.Quarter))
    basic.pause(30)
    music.playTone(392, music.beat(BeatFraction.Quarter))
    basic.pause(30)
    music.playTone(349, music.beat(BeatFraction.Quarter))
    basic.pause(100)
})
